# Generated by Django 3.2.16 on 2022-12-27 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('work_time', models.IntegerField(verbose_name='Время выполнения (мин)')),
                ('questions_count', models.IntegerField(verbose_name='Количество вопросов')),
                ('statisfactorily', models.IntegerField(verbose_name='Удовлетворительно')),
                ('good', models.IntegerField(verbose_name='Хорошо')),
                ('perfect', models.IntegerField(verbose_name='Отлично')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='testapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='ФИО')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время завершения')),
                ('rating', models.FloatField(verbose_name='Проценты')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.profile', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант №1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант №2')),
                ('option3', models.CharField(max_length=200, verbose_name='Вариант №3')),
                ('option4', models.CharField(max_length=200, verbose_name='Вариант №4')),
                ('answer', models.CharField(max_length=200, null=True, verbose_name='Верный ответ')),
                ('weight', models.FloatField(default=1, verbose_name='Вес')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 12, 27, 11, 13, 37, 234000), verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(verbose_name='Опубликован')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('profile_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.profile', verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
