# Generated by Django 3.2.16 on 2022-12-27 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 11, 14, 37, 324000), verbose_name='Дата публикации'),
        ),
    ]
